-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 00:38:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema petshop_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petshop_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petshop_data` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `petshop_data` ;

-- -----------------------------------------------------
-- Table `petshop_data`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`account` (
  `uID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` CHAR(10) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `isAdmin` BIT(1) NULL DEFAULT b'0',
  `email` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `address` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`uID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`category` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(200) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `discount` INT NULL DEFAULT NULL,
  `image` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `hot` INT NULL DEFAULT '0',
  `new` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_product_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `petshop_data`.`category` (`cid`))
ENGINE = InnoDB
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`cart` (
  `maCart` INT NOT NULL AUTO_INCREMENT,
  `accountID` INT NOT NULL,
  `productID` INT NOT NULL,
  `amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`maCart`),
  INDEX `fk_cart_account` (`accountID` ASC) VISIBLE,
  INDEX `fk_cart_product` (`productID` ASC) VISIBLE,
  CONSTRAINT `fk_cart_account`
    FOREIGN KEY (`accountID`)
    REFERENCES `petshop_data`.`account` (`uID`),
  CONSTRAINT `fk_cart_product`
    FOREIGN KEY (`productID`)
    REFERENCES `petshop_data`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`invoice` (
  `maHD` INT NOT NULL AUTO_INCREMENT,
  `accountID` INT NULL DEFAULT NULL,
  `tongGia` FLOAT NULL DEFAULT NULL,
  `ngayXuat` DATETIME NULL DEFAULT NULL,
  `fullName` VARCHAR(200) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`maHD`),
  INDEX `fk_invoice_account` (`accountID` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_account`
    FOREIGN KEY (`accountID`)
    REFERENCES `petshop_data`.`account` (`uID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`soluongdaban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`soluongdaban` (
  `productID` INT NULL DEFAULT NULL,
  `soLuongDaBan` INT NULL DEFAULT NULL,
  INDEX `FK_SoLuongDaBan_Product` (`productID` ASC) VISIBLE,
  CONSTRAINT `FK_SoLuongDaBan_Product`
    FOREIGN KEY (`productID`)
    REFERENCES `petshop_data`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petshop_data`.`tongchitieubanhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petshop_data`.`tongchitieubanhang` (
  `userID` INT NULL DEFAULT NULL,
  `TongChiTieu` FLOAT NULL DEFAULT NULL,
  `TongBanHang` FLOAT NULL DEFAULT NULL,
  INDEX `FK_TongChiTieuBanHang_Account` (`userID` ASC) VISIBLE,
  CONSTRAINT `FK_TongChiTieuBanHang_Account`
    FOREIGN KEY (`userID`)
    REFERENCES `petshop_data`.`account` (`uID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
